[features]
seeds = false
[programs.localnet]
debcre = "BKa2CykVL5EcJ2E7b6u1Q4jfzo6YpuFiypXdDmGs1chN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/krishna-rijal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
